### ISSUE TITLE
Improper acute placement on small letter j

### ISSUE THREAD

**Issue by casperdewith** [silnrsi/font-charis#11]
In Dutch, when you type an ij-with-acute – `i-acute` + `j` + `combining acute accent` – it looks off in Charis:
![charis-ij-acute](https://user-images.githubusercontent.com/35010340/195934793-cb457de7-2a60-48f7-8411-d739c0bd5c06.png)

First of all, the kerning between the `i` and the `j` could be a little tighter in my opinion. But, most importantly, the acute on the `j` comes dangerously close to the ascender of the `k`; the acute is positioned too far to the right. I drew two identical yellow rectangles on top of them to illustrate this.
![charis-ij-acute-differences](https://user-images.githubusercontent.com/35010340/195934790-ed42a842-e1ba-445b-9248-8ee019dfb6cb.png)

For comparison, this is how the letter `i` behaves in the same situation – it has more breathing room:
![charis-ík](https://user-images.githubusercontent.com/35010340/195936477-681da254-c211-4d87-997d-39ea0b55e04b.png)

**What should change:** the positioning of the acute accent on the `j` should be the same as with the `i`, so it should be moved a little to the left.

This issue occurs in the latest version: Charis SIL 6.101.

**Comment by jvgaultney** [comment]
I've improved this for the next release. It will be positioned a tiny bit further left than on the i. Unfortunately the strong design of the acute makes it difficult to avoid all collisions, esp. in bold and italics. To change it more would require width changes for the j, which would negatively affect many users.

**Comment by casperdewith** [comment]
I understand; thank you. Do I have to close this issue now? This is the first issue I ever raised; I don’t know what to do.

**Comment by jvgaultney** [comment]
I'll close it once we've confirmed that it's working better - thanks

**Comment by jvgaultney** [comment]
Improved in v6.200
