### ISSUE TITLE
Turned h (U+A78D, U+02AF) has a round capital but its smallcap is square

### ISSUE THREAD

**Issue by moyogo** [silnrsi/font-charis#14]
/LtnCapTurnedH/LtnSmTurnedH (Ɥ U+A78D LATIN CAPITAL LETTER TURNED H, ɥ U+0265 LATIN SMALL LETTER TURNED H) have a round capital shape for the uppercase /LtnCapTurnedH (Ɥ U+A78D) looking like /LtnSmTurnedH.sc /CyCapChe (Ч U+0427 CYRILLIC CAPITAL LETTER CHE).
Their smallcap /LtnSmTurnedH.sc is square.

/LtnSmTurnedH.sc should probably not be square, as /LtnCapTurnedH is not square, and should be more similar to or the same as /CySmChe.sc.

Current /LtnCapTurnedH/LtnSmTurnedH /LtnSmTurnedH.sc:
<img width="407" alt="Screenshot 2023-01-24 at 13 57 47" src="https://user-images.githubusercontent.com/1923747/214297683-40b26e5a-9453-4a69-80db-78b4d1207344.png">

What  /LtnCapTurnedH/LtnSmTurnedH /LtnSmTurnedH.sc should look like:
<img width="372" alt="Screenshot 2023-01-24 at 13 58 23" src="https://user-images.githubusercontent.com/1923747/214297739-5a49ef0c-9a87-4005-aaa0-1ac6be9d0b28.png">

**Comment by jvgaultney** [comment]
Thanks - I'll get that fixed.
