### ISSUE TITLE
Support for +sups, +subs, +sinf and +frac OpenType tags

### ISSUE THREAD

**Issue by RGB-es** [silnrsi/font-charis#3]
Charis SIL have all sub- and superscripts for numbers, but there is no OpenType option to quickly apply them, they need to be inserted as special characters. It would be really useful to have these options available for at least the numbers (and it would be great to have them for alphabetic characters too).

User case: set a style for footnote anchors that uses real superscripts instead of simulated ones.

**Comment by jvgaultney** [comment]
See https://github.com/silnrsi/font-gentium/issues/4

**Comment by jvgaultney** [comment]
Added in v6.200, although we don't support +sinf, as it is very rarely used.
