### ISSUE TITLE
New symbol: U+2042 ⁂ ASTERISM

### ISSUE THREAD

**Issue by inferno986return** [silnrsi/font-charis#7]
As Charis SIL is an available font in most LaTeX distributions by default I've got very attached to it for documents. 

For my novel project, I am using asterisms for scene breaks. I've created an asterism using Affinity Designer, but I would like to request an official asterism mapped to U+2042 ⁂ ASTERISM.

![asterisk-charissil](https://user-images.githubusercontent.com/1838420/184557294-7b280e50-411b-4105-9195-1dac0abf0c61.png)

**Comment by jvgaultney** [comment]
Thanks - I'll add it to the list of requests. Since you have a solution, and the list is already long for the next couple of versions, it may be a while before we get to it.

**Comment by inferno986return** [comment]
It's a relatively obscure symbol so I expect it to take a while. Glad it's been considered. 😊

**Comment by jvgaultney** [comment]
Added in v6.200
