### ISSUE TITLE
Request for geometric shapes: white circle and fisheye symbols

### ISSUE THREAD

**Issue by zoliky** [silnrsi/font-charis#8]
Hello,
I'm using the "Charis SIL Compact" font in Emacs.
The bullets of the first and second level headings are not rendered properly because the "white circle" and the "fisheye" symbols are missing.

![image](https://i.ibb.co/2S7Tssg/a.jpg)

The bullet points should look like this:

![image](https://i.ibb.co/mGNfsyN/bullet.png)

I used LibreOffice to check for the code values using the DejaVu Sans Mono font:

![image](https://i.ibb.co/cL4MBG2/first.png)

![image](https://i.ibb.co/3RKsR28/second.png)

If these two could be included in Charis SIL, it would be awesome. Thank you.

**Comment by jvgaultney** [comment]
Thanks - I'll add these to the list of requests, although they may not make it in to the next update.

**Comment by jvgaultney** [comment]
Added in v6.200

**Comment by zoliky** [comment]
Thank you so much.
