### ISSUE TITLE
Request: Latin letters glottal i/a/u: U+A7BA-U+A7BF

### ISSUE THREAD

**Issue by dwerning** [silnrsi/font-charis#9]
Dear font developer team,

Egyptological community would be happy to see the following characters added:
U+A7BC LATIN CAPITAL LETTER GLOTTAL I
U+A7BD LATIN SMALL LETTER GLOTTAL I
= egyptological yod
![grafik](https://user-images.githubusercontent.com/33833393/187359984-92af5469-0b47-440a-a2f9-20e5ecee5dfc.png)
The hook may be copied from the lower part of U+A723.
Note that, for capitals, the hook is to be placed before the capitals, not above it.

(Optionally, for Ugaritic purposes, it would be nice to also add analogous:)
U+A7BA LATIN CAPITAL LETTER GLOTTAL A
U+A7BB LATIN SMALL LETTER GLOTTAL A
U+A7BE LATIN CAPITAL LETTER GLOTTAL U
U+A7BF LATIN SMALL LETTER GLOTTAL U

Thank you for considering this request.

(This applies to Charis SIL, [Gentium Plus](https://github.com/silnrsi/font-gentium/issues/14), and Andika alike.)

**Comment by jvgaultney** [comment]
Thanks - these are included in the next version

**Comment by jvgaultney** [comment]
Added in v6.200

**Comment by dwerning** [comment]
Thank you very much.
